name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:
        
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Tailscale
      uses: tailscale/github-action@v2
      with:
          hostname: Github-actions
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

    - name: Deploy to server
      run: |
        ssh -o "StrictHostKeyChecking no" root@docker "
          cd /docker-file/Fridge-Manager
          git pull
          docker compose up --build -d app
        "
