name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
        docker-compose -f docker-compose.yml -f docker-compose.prod.yml push

  deploy:
    
    needs: build
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      env:
        HOST: ${{ secrets.SERVER_HOST }}
        USERNAME: ${{ secrets.SERVER_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${{ env.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no docker-compose.yml ${{ env.USERNAME }}@${{ env.HOST }}:/docker-file/Fridge-Manager/docker-compose.yml
        scp -i private_key -o StrictHostKeyChecking=no docker-compose.prod.yml ${{ env.USERNAME }}@${{ env.HOST }}:/docker-file/Fridge-Manager/docker-compose.prod.yml
        ssh -i private_key -o StrictHostKeyChecking=no ${{ env.USERNAME }}@${{ env.HOST }} << EOF
          cd /docker-file/Fridge-Manager
          echo ${{ env.DOCKER_PASSWORD }} | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml pull
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
        EOF
        rm private_key
